name: Deploy to GitHub Pages on push to main
on:
  push:
    branches:
      - main

jobs:
    build-deploy:
      name: Build and Deploy Docusaurus to GitHub Pages
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm

        - name: Install dependencies
          run: npm ci --ignore-scripts
        - name: Build website
          run: npm run build

        # Popular action to deploy to GitHub Pages:
        # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Build output to publish to the `gh-pages` branch:
            publish_dir: ./build