name: Deploy to Github Pages on PR
on:
  pull_request:
    branches:
      - main
jobs:
  pr-description-add:
    name: PR Description Add
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    timeout-minutes: 1
    steps:
      - uses: bcgov-nr/action-pr-description-add@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---
            Thanks for the PR!

            Deployments, as required, will be available below:
            - [Frontend](https://bcgov.github.io/event-driven-architecture-guidelines/pr/${{github.actor}}/${{github.event.number}})


  deploys:
    runs-on: ubuntu-22.04
    defaults:
        run:
          working-directory: ./Event-Driven-Architecture
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Event-Driven-Architecture/package-lock.json
  
      - name: Install dependencies
        run:  npm ci --ignore-scripts
      - name: Build website
        run: |
          export BASE_URL="/event-driven-architecture-guidelines/pr/${{github.actor}}/${{github.event.number}}" && npm run build
  
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./Event-Driven-Architecture/build
          destination_dir: pr/${{github.actor}}/${{github.event.number}}
